### ISSUE TITLE
add a new dataset

### ISSUE THREAD

**Issue by zhouyaqian666** [BaiShuanghao/Prompt-based-Distribution-Alignment#3]
Hello, When I added a new dataset MI3DOR, the error" ValueError: The requested one is expected to belong to ['Digit5', 'VisDA17', 'CIFARSTL', 'Office31', 'DomainNet', 'OfficeHome', 'miniDomainNet', 'PACS', 'VLCS', 'FMoW', 'IWildCam', 'Camelyon17', 'CIFAR10C', 'CIFAR100C', 'DigitsDG', 'DigitSingle', 'OfficeHomeDG', 'CIFAR10', 'CIFAR100', 'SVHN', 'STL10'], but got [MI3DOR] (do you mean [CIFAR10]?)”. How to correctly add a new dataset? Thanks.

**Comment by BaiShuanghao** [comment]
The code is based on the **[dassl](https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/DATASETS.md)** library. There are some examples in the link of the library, and you can refer to these examples. By the way, you need to add **@DATASET_REGISTRY.register()** before the definition of the class to register your own dataset.
